enum TypeKeys {
  UPDATE_DOCUMENT_CONTENTS = 'DOCUMENT:UPDATE',
  UPDATE_DOCUMENT_TITLE = 'DOCUMENT:UPDATE_TITLE',
  TOGGLE_INLINE_STYLE = 'DOCUMENT:TOGGLE_INLINE_STYLE',
  TOGGLE_BLOCK_STYLE = 'DOCUMENT:TOGGLE_BLOCK_STYLE'
}

export default TypeKeys;
